version: '3.8'

services:
  app:
    build: .
    container_name: nextjs-app
    restart: always
    expose:
      - 3000
    networks:
      - app-network

  nginx:
    image: nginx:1.24
    container_name: nginx-proxy
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
