version: "3.8"

services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: nextjs-app
    restart: always
    ports:
      - "3000:3000"
    networks:
      - nextjs-network

  nginx:
    image: nginx:latest
    container_name: nginx
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx.config:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - nextjs-network

networks:
  nextjs-network:
    driver: bridge

