name: Deploy Next.js App to EC2

on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Copy files to EC2
        uses: appleboy/scp-action@v0.1.3
        with:
          host: 13.233.117.94
          username: ubuntu
          key: ${{ secrets.EC2_KEY }}
          source: "."
          target: "~/nextjs-app"

      - name: SSH into EC2 and deploy app
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          script: |
            cd ~/nextjs-app
            sudo apt update
            sudo apt install -y nodejs npm
            npm install
            npm run build
            pm2 delete app || true
            pm2 start npm --name app -- start
